# Generated by Django 3.2 on 2021-04-30 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog2', '0002_auto_20210430_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='courses_pics'),
        ),
    ]
