# Generated by Django 3.2 on 2021-04-30 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog2', '0003_course_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='duree',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
