# Generated by Django 3.2 on 2021-05-10 11:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog2', '0007_auto_20210510_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='duree',
            field=models.IntegerField(blank=True, null=True, verbose_name='Duration'),
        ),
        migrations.AlterField(
            model_name='course',
            name='is_new',
            field=models.BooleanField(default=False, verbose_name='New Course or not'),
        ),
        migrations.AlterField(
            model_name='course',
            name='post_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation Date'),
        ),
    ]
