# Generated by Django 3.2 on 2021-05-11 17:12

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog2', '0008_auto_20210510_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='content2',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
