# Generated by Django 3.2 on 2021-05-11 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog2', '0009_auto_20210511_1712'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='content2',
            new_name='code_snippet',
        ),
    ]
