# Generated by Django 3.2 on 2021-05-17 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='training-pics/')),
                ('title', models.CharField(max_length=40)),
                ('content', models.TextField()),
            ],
        ),
    ]
