# Generated by Django 3.2 on 2021-05-17 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to='courses_for_pics')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course', to='formations.training')),
            ],
        ),
    ]
