# Generated by Django 3.2 on 2021-05-20 20:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0004_course_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='training_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Creation Date'),
        ),
    ]
